name: Release

on:
  push:
    branches-ignore:
      - '*'
    tags:
      - '*.*.*' # push to versioned tag will trigger this build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set version
        id: vars
        uses: battila7/get-version-action@v2
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.version }}
          release_name: ${{ steps.vars.outputs.version }}
          draft: false
          prerelease: false
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TGBOT_RADIANCEDEPLOY_TO }}
          token: ${{ secrets.TGBOT_RADIANCEDEPLOY_TOKEN }}
          message: |
            PHP SDK Wrapper ${{ steps.vars.outputs.version }} has been released.
            https://github.com/radianceteam/ton-client-php/releases/tag/${{ steps.vars.outputs.version }}
          