name: Tests

on: [push]

jobs:
  run:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        php-versions: ['7.4']

    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}

    steps:
    - uses: actions/checkout@v1

    - name: Install PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Check PHP Version
      run: php -v

    - name: Download PHP Installer
      run: php -r "file_put_contents('installer.php', fopen('https://raw.githubusercontent.com/radianceteam/ton-client-php-ext/master/installer.php', 'r'));"
      
    - name: Install PHP Extension (Windows)
      if: matrix.operating-system == 'windows-latest'
      run: php installer.php -v 1.5.1

    - name: Install PHP Extension (Ubuntu/Mac)
      if: matrix.operating-system != 'windows-latest'
      run: sudo php installer.php -v 1.5.1

    - name: Test PHP Extension
      run: php installer.php -v 1.5.1 -T

    - name: Check PHP Extensions
      run: php -m

    - name: Check Composer Version
      run: composer -V

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Setup Environment (Ubuntu)
      if: matrix.operating-system == 'ubuntu-latest'
      run: |
        docker run -d --name local-node -e USER_AGREEMENT=yes -p8888:80 tonlabs/local-node

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    
    - name: Run test suite
      run: composer test
